name: Release Branch

on:
  push:
    branches: [ ShazIndia-changemainfile ]

  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain version (e.g., stable, nightly)'
        required: true
        type: string
        default: "stable"
      target:
        description: 'Compilation target (e.g., x86_64-unknown-linux-gnu)'
        required: true
        type: string
        default: "x86_64-unknown-linux-gnu"
      components:
        description: 'Rust components to install (comma-separated, e.g., clippy, rustfmt, llvm-tools)'
        required: false
        type: string
        default: "clippy"
      release_version:
        description: 'Version of the release (e.g., 1.0.0)'
        required: true
        type: string
        default: '1.0.0'
      base_branch:
        description: 'Base branch to cut the release from (e.g., main or develop)'
        required: true
        type: string
        default: 'main'
      git_username:
        description: 'Git username for the commit'
        required: true
        type: string
        default: 'GitHub Actions Bot'
      git_email:
        description: 'Git email for the commit'
        type: string
        required: true
        default: 'actions@github.com'

jobs:
 Release-Stage:
    uses: ShazIndia/Actions-Reusable-Workflows/.github/workflows/release-workflow.yml@main
    with:
      release_version: "1.0.0"
      base_branch: "main"
      git_username: "ShazIndia"
      git_email: "shashi11107@gmail.com"

 Build-Stage:
    uses: ShazIndia/Actions-Reusable-Workflows/.github/workflows/buildtest-workflow.yml@main
    with:
      toolchain: "stable"
      target: "x86_64-unknown-linux-gnu"
      components: "clippy"

  # Optionally: Add Rust build, test, or lint steps here if required
 
